/**
 * Report Content Configuration
 * 
 * Data-driven presentation blocks configured from project presentation materials.
 * Main presentation structure containing 6 distinct topic blocks with large typography.
 */

export const reportMetadata = {
  title: "Real-Time 6D Pose Estimation of a Rigid Training Bar",
  subtitle: "Using Geometry-Based and Data-Driven Approaches",
  authors: ["Computer Vision Final Project", "UTN Studies"],
  date: "September 2026",
  version: "1.0",
  tags: ["6-DoF Pose Estimation", "PnP", "EKF", "CNN", "Meta Quest GT", "Dual-Exposure"]
};

export const reportBlocks = [
  {
    id: "hero",
    layout: "hero",
    badge: "Computer Vision Final Project Presentation",
    title: "Real-Time 6D Pose Estimation of a Rigid Training Bar",
    subtitle: "Using Geometry-Based and Data-Driven Approaches",
    stats: [
      { label: "Hardware Target", value: "Raspberry Pi 4B", subtext: "Real-time edge compute" },
      { label: "Camera Stream", value: "640×400 @ 309 fps", subtext: "OV9281 Global Shutter" },
      { label: "Ground Truth", value: "Meta Quest Pro", subtext: "90 Hz Inside-Out Tracking" },
      { label: "Dataset Size", value: "42,000+ pts", subtext: "Synchronized 6-DoF frames" }
    ]
  },
  {
    id: "embodied-systems",
    layout: "image-right",
    tag: "Embodied Systems",
    title: "Perception for Physical Interaction",
    subsections: [
      {
        title: "Robotic Strength Training Device",
        items: [
          "From 5 to 50 kg dynamic motorized load",
          "Instant closed-loop torque control",
          "Limited perceptual information about the user"
        ]
      },
      {
        title: "Missing State Information:",
        items: [
          "User’s biomechanical body pose",
          "Real-time 6-DoF spatial position of the bar",
          "Environmental context & interaction boundary"
        ]
      }
    ],
    image: {
      src: "/images/image5.png",
      alt: "Robotic Strength Training Device",
      caption: "Robotic strength training device with motorized resistance",
      isEnlargedCrop: true
    }
  },
  {
    id: "computer-vision",
    layout: "image-left",
    tag: "Computer Vision",
    title: "6D Pose Estimation of a Rigid Training Bar",
    subsections: [
      {
        title: "Position estimation of a training bar enables:",
        items: [
          "Real-time dynamic safety & load shedding",
          "Automated exercise classification & repetition counting",
          "Immersive interactive workout gamification in VR/AR"
        ]
      },
      {
        title: "System Constraints",
        items: [
          "Edge compute budget (Raspberry Pi 4B)",
          "Low-latency real-time tracking pipeline"
        ]
      }
    ],
    image: {
      src: "/images/image7.gif",
      alt: "Simulation of workout in VR, Gaming footage is Generated by AI",
      caption: "Simulation of workout in VR, Gaming footage is Generated by AI"
    }
  },
  {
    id: "possible-implementations",
    layout: "image-right",
    tag: "Possible Implementations",
    title: "Geometry-Based and Data-Driven Approaches",
    subsections: [
      {
        title: "Geometry-Based Tracking (PnP / EKF)",
        items: [
          "Deterministic closed-form Perspective-n-Point pose solvers",
          "Minimal computational overhead (ideal for edge SBC deployment)",
          "Requires calibrated optical retroreflective markers & known geometry"
        ]
      },
      {
        title: "Data-Driven Approaches (CNN / Deep Learning)",
        items: [
          "Markerless direct 6-DoF pose regression from intensity frames",
          "High compute & memory footprint during neural inference",
          "Requires large-scale annotated multi-view training datasets"
        ]
      }
    ],
    image: {
      src: "/images/image4.png",
      alt: "Infrared retro-reflective markers surgical navigation comparison",
      caption: "Source: An Accurate Recognition of Infrared Retro-Reflective Markers in Surgical Navigation Systems-Level Quality Improvement"
    }
  },
  {
    id: "hardware-camera",
    layout: "dual-image-right",
    tag: "Hardware",
    title: "Camera Module & Illumination",
    subsections: [
      {
        title: "Global Shutter Camera",
        items: [
          "OV9281 Monochrome sensor",
          "High frame rate: 640×400 @ 309 fps",
          "Zero motion blur with RAW8 / RAW10 direct readout",
          "Narrowband Infrared Optical Pass Filter"
        ]
      },
      {
        title: "Active Infrared 3-LED Array",
        items: [
          "850 nm high-intensity optical emission",
          "Integrated 40V to 12V buck step-down converter",
          "Adjustable pulse intensity & illumination brightness"
        ]
      }
    ],
    images: [
      {
        src: "/images/image1.png",
        alt: "OV9281 Camera Module",
        caption: "OV9281 Monochrome Global Shutter Camera"
      },
      {
        src: "/images/image3.png",
        alt: "Infrared 3 LED Array Board",
        caption: "850 nm Infrared 3-LED Array Board"
      }
    ]
  },
  {
    id: "hardware-rigidbody",
    layout: "image-left",
    tag: "Hardware",
    title: "Rigid Body for Position Estimation",
    subsections: [
      {
        title: "The Training Bar Target",
        items: [
          "4 high-contrast retroreflective optical markers",
          "Rigid calibrated 3D geometric marker constellation",
          "Custom 3D-printed mechanical housing for VR controller"
        ]
      },
      {
        title: "Meta Quest Touch Pro (Ground Truth Reference)",
        items: [
          "Independent 6-DoF inside-out computer vision tracking",
          "Translational worst-case error: 3.2 ± 2.4 mm MAE",
          "Rotational worst-case error: 2.1 ± 1.0° MAE",
          "90 Hz high-frequency trajectory streaming"
        ]
      }
    ],
    image: {
      src: "/images/image6.png",
      alt: "Rigid training bar with 4 markers and Meta Quest Touch Pro mount",
      caption: "Rigid training bar prototype with 4 optical markers and Meta Quest Touch Pro housing"
    }
  },
  {
    id: "data-acquisition",
    layout: "image-right",
    tag: "Data Acquisition",
    title: "Custom Dataset Collection",
    subsections: [
      {
        title: "Synchronized Multi-Modal Stream Capture",
        items: [
          "Synchronous camera video & 6-DoF controller ground-truth logs",
          "10-minute continuous recording duration",
          "72 Datapoints per second capture rate",
          "42,000+ spatial-temporal sample points across 3D poses & rotations"
        ]
      }
    ],
    image: {
      src: "/images/image2.gif",
      alt: "Dataset collection and 3D trajectory tracking preview",
      caption: "Synchronized dual-stream video and 6-DoF controller ground-truth recording"
    }
  }
];
